// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * The neoma slash-command set. Every command inserts real, portable Markdown
 * (or opens a real modal / runs a real app command) — there are no fake or
 * placeholder actions. AI commands are present but disabled until an AI
 * plugin is installed, and never require the network.
 *
 * These are the single source of truth: they register into the slash registry
 * AND (via registerSlashCommands) into the global command palette, so `/` and
 * `Ctrl/Cmd+K` share identical definitions.
 */
import type { EditorView } from '@codemirror/view'
import type { SlashCommand } from './types'
import { registerSlashCommand } from './registry'
import { insertSnippet, wrapSelection, insertText } from './insert'
import { registerCommand, runCommand, getCommand } from '@/commands/registry'
import { getActiveView } from '../activeView'
import { useUi } from '@/app/uiStore'
import { useTabs } from '@/app/tabsStore'
import { useVault } from '@/app/vaultStore'
import { isoDate } from '@/utils/dates'
import { useStudy, cardsForNote, cardsForVault } from '@/study/studyStore'
import { basename } from '@/utils/paths'

const snippet = (t: string) => (ctx: { view: EditorView }) => insertSnippet(ctx.view, t)
const wrap = (b: string, a: string, ph?: string) => (ctx: { view: EditorView }) =>
  wrapSelection(ctx.view, b, a, ph)

/** Open the attachment picker for the active note. */
function openAttachmentPicker(mode: 'embed' | 'link' = 'embed'): void {
  const tabs = useTabs.getState()
  const active = tabs.tabs.find((t) => t.id === tabs.activeId)
  if (active?.type === 'note' && active.path)
    useUi.getState().setAttachmentPickerFor(active.path, mode)
}

/** Review the flashcards in the active note. */
async function reviewCurrentNote(): Promise<void> {
  const tabs = useTabs.getState()
  const active = tabs.tabs.find((t) => t.id === tabs.activeId)
  if (active?.type !== 'note' || !active.path) return
  const cards = await cardsForNote(active.path)
  if (!cards.length) {
    useUi.getState().toast('No flashcards on this page yet', 'info')
    return
  }
  useStudy.getState().openReview(basename(active.path).replace(/\.md$/i, ''), cards)
}

/** Review every flashcard in the vault. */
async function reviewWholeVault(): Promise<void> {
  const cards = await cardsForVault()
  if (!cards.length) {
    useUi.getState().toast('No flashcards found in this vault', 'info')
    return
  }
  useStudy.getState().openReview('All flashcards', cards)
}

export const SLASH_COMMANDS: SlashCommand[] = [
  // ─────────────────────────── Basic Text ───────────────────────────
  {
    id: 'text.paragraph',
    title: 'Paragraph',
    category: 'Basic Text',
    icon: 'text',
    description: 'Plain text',
    keywords: ['body', 'p'],
    example: 'Just start writing.',
    run: snippet('${}'),
  },
  {
    id: 'text.h1',
    title: 'Heading 1',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Large section heading',
    keywords: ['h1', 'title'],
    example: '# Heading',
    contexts: ['heading'],
    run: snippet('# ${Heading 1}'),
  },
  {
    id: 'text.h2',
    title: 'Heading 2',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Medium section heading',
    keywords: ['h2'],
    example: '## Heading',
    contexts: ['heading'],
    run: snippet('## ${Heading 2}'),
  },
  {
    id: 'text.h3',
    title: 'Heading 3',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Small section heading',
    keywords: ['h3'],
    example: '### Heading',
    contexts: ['heading'],
    run: snippet('### ${Heading 3}'),
  },
  {
    id: 'text.h4',
    title: 'Heading 4',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Sub-subsection',
    keywords: ['h4'],
    contexts: ['heading'],
    run: snippet('#### ${Heading 4}'),
  },
  {
    id: 'text.h5',
    title: 'Heading 5',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Minor heading',
    keywords: ['h5'],
    contexts: ['heading'],
    run: snippet('##### ${Heading 5}'),
  },
  {
    id: 'text.h6',
    title: 'Heading 6',
    category: 'Basic Text',
    icon: 'heading',
    description: 'Smallest heading',
    keywords: ['h6'],
    contexts: ['heading'],
    run: snippet('###### ${Heading 6}'),
  },
  {
    id: 'text.bold',
    title: 'Bold',
    category: 'Basic Text',
    icon: 'bold',
    description: 'Bold text',
    shortcut: 'Mod+B',
    keywords: ['strong'],
    example: '**bold**',
    run: wrap('**', '**', 'bold text'),
  },
  {
    id: 'text.italic',
    title: 'Italic',
    category: 'Basic Text',
    icon: 'italic',
    description: 'Italic text',
    shortcut: 'Mod+I',
    keywords: ['emphasis'],
    example: '*italic*',
    run: wrap('*', '*', 'italic text'),
  },
  {
    id: 'text.underline',
    title: 'Underline',
    category: 'Basic Text',
    icon: 'underline',
    description: 'Underlined text',
    keywords: ['u'],
    example: '<u>underline</u>',
    run: wrap('<u>', '</u>', 'underlined text'),
  },
  {
    id: 'text.strike',
    title: 'Strikethrough',
    category: 'Basic Text',
    icon: 'strike',
    description: 'Crossed-out text',
    shortcut: 'Mod+Shift+X',
    keywords: ['strike', 'delete'],
    example: '~~struck~~',
    run: wrap('~~', '~~', 'struck text'),
  },
  {
    id: 'text.highlight',
    title: 'Highlight',
    category: 'Basic Text',
    icon: 'highlight',
    description: 'Highlighted text (yellow)',
    shortcut: 'Mod+Shift+H',
    keywords: ['mark'],
    example: '==highlight==',
    run: wrap('==', '==', 'highlighted text'),
  },
  {
    id: 'text.highlight-color',
    title: 'Coloured Highlight',
    category: 'Basic Text',
    icon: 'colorText',
    description: 'Highlight in a chosen colour',
    keywords: ['mark', 'colour', 'color'],
    example: '<mark data-color="blue">…</mark>',
    run: wrap('<mark data-color="blue">', '</mark>', 'highlighted text'),
  },
  {
    id: 'text.superscript',
    title: 'Superscript',
    category: 'Basic Text',
    icon: 'sup',
    description: 'Raised text (x²)',
    keywords: ['power', 'exponent'],
    example: 'x<sup>2</sup>',
    run: wrap('<sup>', '</sup>', '2'),
  },
  {
    id: 'text.subscript',
    title: 'Subscript',
    category: 'Basic Text',
    icon: 'sub',
    description: 'Lowered text (xₙ)',
    keywords: ['index'],
    example: 'x<sub>n</sub>',
    run: wrap('<sub>', '</sub>', 'n'),
  },
  {
    id: 'text.inline-code',
    title: 'Inline Code',
    category: 'Basic Text',
    icon: 'code',
    description: 'Monospace inline code',
    shortcut: 'Mod+E',
    keywords: ['monospace'],
    example: '`code`',
    run: wrap('`', '`', 'code'),
  },
  {
    id: 'text.code-block',
    title: 'Code Block',
    category: 'Basic Text',
    icon: 'code',
    description: 'Fenced code with highlighting',
    keywords: ['fence', 'snippet'],
    example: '```js\n…\n```',
    contexts: ['code'],
    run: snippet('```${language}\n${code}\n```'),
  },
  {
    id: 'text.quote',
    title: 'Quote',
    category: 'Basic Text',
    icon: 'quote',
    description: 'Blockquote',
    keywords: ['blockquote'],
    example: '> quote',
    contexts: ['quote'],
    run: snippet('> ${quote}'),
  },
  {
    id: 'text.divider',
    title: 'Divider',
    category: 'Basic Text',
    icon: 'divider',
    description: 'Horizontal rule',
    keywords: ['hr', 'line', 'separator'],
    example: '---',
    run: snippet('---\n${}'),
  },
  {
    id: 'text.columns',
    title: 'Columns',
    category: 'Basic Text',
    icon: 'columns',
    description: 'Two columns side by side (add ||| for more)',
    keywords: ['column', 'layout', 'side by side', 'grid'],
    example: ':::columns\nLeft\n|||\nRight\n:::',
    run: snippet(':::columns\n${Left column}\n|||\n${Right column}\n:::\n'),
  },

  // ─────────────────────────── Lists ───────────────────────────
  {
    id: 'list.bullet',
    title: 'Bullet List',
    category: 'Lists',
    icon: 'list',
    description: 'Unordered list',
    keywords: ['ul', 'unordered'],
    example: '- item',
    contexts: ['list'],
    run: snippet('- ${item}'),
  },
  {
    id: 'list.numbered',
    title: 'Numbered List',
    category: 'Lists',
    icon: 'ordered',
    description: 'Ordered list',
    keywords: ['ol', 'ordered'],
    example: '1. item',
    contexts: ['list'],
    run: snippet('1. ${item}'),
  },
  {
    id: 'list.checkbox',
    title: 'Checkbox List',
    category: 'Lists',
    icon: 'task',
    description: 'To-do checkboxes',
    keywords: ['todo', 'task', 'check'],
    example: '- [ ] task',
    contexts: ['list'],
    run: snippet('- [ ] ${task}'),
  },
  {
    id: 'list.nested',
    title: 'Nested List',
    category: 'Lists',
    icon: 'list',
    description: 'List with a sub-item',
    keywords: ['indent', 'sub'],
    example: '- item\n  - sub-item',
    contexts: ['list'],
    run: snippet('- ${item}\n  - ${sub-item}'),
  },
  {
    id: 'list.toggle',
    title: 'Toggle List',
    category: 'Lists',
    icon: 'toggle',
    description: 'Collapsible section',
    keywords: ['fold', 'collapse', 'details'],
    example: '> [!toggle]- Title',
    contexts: ['list'],
    run: snippet('> [!toggle]- ${Title}\n> ${content}'),
  },
  {
    id: 'list.definition',
    title: 'Definition List',
    category: 'Lists',
    icon: 'book',
    description: 'Term and definition',
    keywords: ['dl', 'glossary'],
    example: 'Term\n: Definition',
    run: snippet('${Term}\n: ${Definition}'),
  },

  // ─────────────────────────── Callouts ───────────────────────────
  {
    id: 'callout.note',
    title: 'Note',
    category: 'Callouts',
    icon: 'callout',
    description: 'Note callout',
    keywords: ['callout', 'info box'],
    example: '> [!note]',
    run: snippet('> [!note] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.tip',
    title: 'Tip',
    category: 'Callouts',
    icon: 'callout',
    description: 'Tip callout',
    keywords: ['callout', 'hint'],
    run: snippet('> [!tip] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.important',
    title: 'Important',
    category: 'Callouts',
    icon: 'callout',
    description: 'Important callout',
    keywords: ['callout', 'warning'],
    run: snippet('> [!important] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.warning',
    title: 'Warning',
    category: 'Callouts',
    icon: 'callout',
    description: 'Warning callout',
    keywords: ['callout', 'caution'],
    run: snippet('> [!warning] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.success',
    title: 'Success',
    category: 'Callouts',
    icon: 'callout',
    description: 'Success callout',
    keywords: ['callout', 'done', 'check'],
    run: snippet('> [!success] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.error',
    title: 'Error',
    category: 'Callouts',
    icon: 'callout',
    description: 'Error callout',
    keywords: ['callout', 'danger', 'fail'],
    run: snippet('> [!error] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.info',
    title: 'Information',
    category: 'Callouts',
    icon: 'callout',
    description: 'Information callout',
    keywords: ['callout', 'info'],
    run: snippet('> [!info] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.question',
    title: 'Question',
    category: 'Callouts',
    icon: 'callout',
    description: 'Question callout',
    keywords: ['callout', 'faq', 'help'],
    run: snippet('> [!question] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.example',
    title: 'Example',
    category: 'Callouts',
    icon: 'callout',
    description: 'Example callout',
    keywords: ['callout', 'sample'],
    run: snippet('> [!example] ${Title}\n> ${content}'),
  },
  {
    id: 'callout.quote-block',
    title: 'Quote Callout',
    category: 'Callouts',
    icon: 'quote',
    description: 'Quotation callout',
    keywords: ['callout', 'cite'],
    run: snippet('> [!quote] ${Source}\n> ${quotation}'),
  },

  // ─────────────────────────── Mathematics ───────────────────────────
  {
    id: 'math.inline',
    title: 'Inline Equation',
    category: 'Mathematics',
    icon: 'math',
    description: 'Maths inside a sentence',
    keywords: ['latex', 'katex'],
    example: '$e^{i\\pi}+1=0$',
    contexts: ['math'],
    run: wrap('$', '$', 'x'),
  },
  {
    id: 'math.display',
    title: 'Display Equation',
    category: 'Mathematics',
    icon: 'math',
    description: 'Centred display equation',
    keywords: ['latex', 'block'],
    example: '$$\\int e^{-x^2}dx$$',
    contexts: ['math'],
    run: snippet('$$\n${e = mc^2}\n$$'),
  },
  {
    id: 'math.matrix',
    title: 'Matrix',
    category: 'Mathematics',
    icon: 'math',
    description: 'Matrix (bmatrix)',
    keywords: ['linear algebra'],
    example: '\\begin{bmatrix}…\\end{bmatrix}',
    contexts: ['math'],
    run: snippet('$$\n\\begin{bmatrix} ${a} & ${b} \\\\ ${c} & ${d} \\end{bmatrix}\n$$'),
  },
  {
    id: 'math.cases',
    title: 'Cases',
    category: 'Mathematics',
    icon: 'math',
    description: 'Piecewise definition',
    keywords: ['piecewise'],
    contexts: ['math'],
    run: snippet(
      '$$\nf(x) = \\begin{cases} ${a} & ${x > 0} \\\\ ${b} & ${x \\le 0} \\end{cases}\n$$',
    ),
  },
  {
    id: 'math.fraction',
    title: 'Fraction',
    category: 'Mathematics',
    icon: 'math',
    description: 'Fraction template',
    keywords: ['frac', 'divide'],
    example: '\\frac{a}{b}',
    contexts: ['math'],
    run: snippet('\\frac{${a}}{${b}}'),
  },
  {
    id: 'math.summation',
    title: 'Summation',
    category: 'Mathematics',
    icon: 'math',
    description: 'Sigma sum',
    keywords: ['sum', 'sigma'],
    contexts: ['math'],
    run: snippet('\\sum_{${i=1}}^{${n}} ${a_i}'),
  },
  {
    id: 'math.integral',
    title: 'Integral',
    category: 'Mathematics',
    icon: 'math',
    description: 'Definite integral',
    keywords: ['integrate'],
    contexts: ['math'],
    run: snippet('\\int_{${a}}^{${b}} ${f(x)}\\,dx'),
  },
  {
    id: 'math.limit',
    title: 'Limit',
    category: 'Mathematics',
    icon: 'math',
    description: 'Limit expression',
    keywords: ['lim'],
    contexts: ['math'],
    run: snippet('\\lim_{${x \\to \\infty}} ${f(x)}'),
  },
  {
    id: 'math.derivative',
    title: 'Derivative',
    category: 'Mathematics',
    icon: 'math',
    description: 'Ordinary derivative',
    keywords: ['diff', 'ddx'],
    contexts: ['math'],
    run: snippet('\\frac{d${y}}{d${x}}'),
  },
  {
    id: 'math.partial',
    title: 'Partial Derivative',
    category: 'Mathematics',
    icon: 'math',
    description: 'Partial derivative',
    keywords: ['gradient'],
    contexts: ['math'],
    run: snippet('\\frac{\\partial ${L}}{\\partial ${w}}'),
  },
  {
    id: 'math.vector',
    title: 'Vector',
    category: 'Mathematics',
    icon: 'math',
    description: 'Bold vector',
    keywords: ['bold'],
    contexts: ['math'],
    run: snippet('\\mathbf{${v}}'),
  },
  {
    id: 'math.probability',
    title: 'Probability',
    category: 'Mathematics',
    icon: 'math',
    description: 'Conditional probability',
    keywords: ['bayes'],
    example: 'P(A\\mid B)',
    contexts: ['math'],
    run: snippet('P(${A} \\mid ${B}) = \\frac{P(${B} \\mid ${A})P(${A})}{P(${B})}'),
  },
  {
    id: 'math.statistics',
    title: 'Statistics',
    category: 'Mathematics',
    icon: 'math',
    description: 'Normal distribution',
    keywords: ['gaussian', 'mean'],
    contexts: ['math'],
    run: snippet('${X} \\sim \\mathcal{N}(${\\mu}, ${\\sigma^2})'),
  },
  {
    id: 'math.greek',
    title: 'Greek Symbols',
    category: 'Mathematics',
    icon: 'math',
    description: 'Common Greek letters',
    keywords: ['alpha', 'beta', 'lambda'],
    contexts: ['math'],
    run: snippet('\\${alpha} \\beta \\gamma \\delta \\theta \\lambda \\mu \\pi \\sigma'),
  },
  {
    id: 'math.logic',
    title: 'Logic Symbols',
    category: 'Mathematics',
    icon: 'math',
    description: 'Logic & set operators',
    keywords: ['forall', 'exists', 'implies'],
    contexts: ['math'],
    run: snippet('\\forall ${x} \\in ${S}: ${P(x)} \\implies ${Q(x)}'),
  },
  {
    id: 'math.ml',
    title: 'Common ML Equation',
    category: 'Mathematics',
    icon: 'math',
    description: 'Linear model y = Xβ + ε',
    keywords: ['machine learning', 'regression'],
    contexts: ['math'],
    run: snippet('$$\n\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}\n$$'),
  },
  {
    id: 'math.gradient-descent',
    title: 'Common AI Equation',
    category: 'Mathematics',
    icon: 'math',
    description: 'Gradient-descent update',
    keywords: ['ai', 'gradient descent'],
    contexts: ['math'],
    run: snippet('$$\n\\theta_{t+1} = \\theta_t - \\eta \\nabla_\\theta L(\\theta_t)\n$$'),
  },

  // ─────────────────────────── Research ───────────────────────────
  {
    id: 'research.literature',
    title: 'Literature Note',
    category: 'Research',
    icon: 'book',
    description: 'Structured reading note',
    keywords: ['paper', 'reading'],
    run: snippet(
      '## Citation\n\n> ${authors, title, venue, year} [@${citekey}]\n\n## Research question\n\n- ${question}\n\n## Main findings\n\n- ${finding}\n\n## Personal interpretation\n\n- ${interpretation}',
    ),
  },
  {
    id: 'research.question',
    title: 'Research Question',
    category: 'Research',
    icon: 'book',
    description: 'Frame a research question',
    keywords: ['rq'],
    run: snippet(
      '## Question\n\n- ${question}\n\n## Motivation\n\n- ${why}\n\n## Possible methods\n\n- ${method}',
    ),
  },
  {
    id: 'research.experiment',
    title: 'Experiment Log',
    category: 'Research',
    icon: 'book',
    description: 'Experiment run record',
    keywords: ['run', 'lab'],
    run: snippet(
      '## Hypothesis\n\n- ${hypothesis}\n\n## Parameters\n\n| Parameter | Value |\n| --------- | ----- |\n| ${p} | ${v} |\n\n## Results\n\n- ${result}\n\n## Next experiment\n\n- ${next}',
    ),
  },
  {
    id: 'research.supervisor',
    title: 'Supervisor Meeting',
    category: 'Research',
    icon: 'book',
    description: 'Meeting notes',
    keywords: ['meeting'],
    run: snippet(
      '## Date\n\n${date}\n\n## Discussion\n\n- ${topic}\n\n## Actions\n\n- [ ] ${action}\n\n## Next meeting\n\n- ${when}',
    ),
  },
  {
    id: 'research.journal',
    title: 'Daily Research Journal',
    category: 'Research',
    icon: 'book',
    description: "Today's journal sections",
    keywords: ['diary'],
    run: snippet(
      '## Objectives\n\n- ${objective}\n\n## Findings\n\n- ${finding}\n\n## Next actions\n\n- [ ] ${next}',
    ),
  },
  {
    id: 'research.reading',
    title: 'Reading Note',
    category: 'Research',
    icon: 'book',
    description: 'Quick reading capture',
    keywords: ['book', 'article'],
    run: snippet('**Source:** ${source}\n\n**Key idea:** ${idea}\n\n**Quote:** > ${quote}'),
  },
  {
    id: 'research.citation',
    title: 'Citation',
    category: 'Research',
    icon: 'book',
    description: 'Pandoc citation key',
    keywords: ['cite', 'ref'],
    example: '[@smith2025]',
    run: snippet('[@${citekey}]'),
  },
  {
    id: 'research.reference',
    title: 'Reference',
    category: 'Research',
    icon: 'book',
    description: 'Reference list entry',
    keywords: ['bibliography'],
    run: snippet('- ${Author}, *${Title}*, ${Year}.'),
  },
  {
    id: 'research.doi',
    title: 'DOI',
    category: 'Research',
    icon: 'book',
    description: 'DOI frontmatter/link',
    keywords: ['doi'],
    run: snippet('doi: ${10.xxxx/xxxxx}'),
  },
  {
    id: 'research.bibtex',
    title: 'BibTeX',
    category: 'Research',
    icon: 'code',
    description: 'BibTeX entry block',
    keywords: ['bib', 'reference'],
    run: snippet(
      '```bibtex\n@article{${key},\n  title   = {${Title}},\n  author  = {${Author}},\n  year    = {${Year}}\n}\n```',
    ),
  },
  {
    id: 'research.idea',
    title: 'Research Idea',
    category: 'Research',
    icon: 'book',
    description: 'Capture an idea',
    keywords: ['idea'],
    run: snippet('> [!idea] ${Idea}\n> ${detail}'),
  },

  // ─────────────────────────── Study ───────────────────────────
  {
    id: 'study.lecture',
    title: 'Lecture Note',
    category: 'Study',
    icon: 'book',
    description: 'Lecture note template',
    keywords: ['class', 'week'],
    run: snippet(
      '## Source material\n\n${referenced content}\n\n## My explanation\n\n${in my own words}\n\n## What I do not understand\n\n- ${question}\n\n## Exam summary\n\n- ${key point}',
    ),
  },
  {
    id: 'study.flashcard',
    title: 'Flashcard',
    category: 'Study',
    icon: 'flashcard',
    description: 'Question / answer pair',
    keywords: ['revision', 'srs'],
    example: 'Question:: …\\nAnswer:: …',
    run: snippet('Question:: ${question}\nAnswer:: ${answer}'),
  },
  {
    id: 'study.review',
    title: 'Review Flashcards',
    category: 'Study',
    icon: 'flashcard',
    description: 'Review this page’s flashcards',
    keywords: ['revise', 'srs', 'study', 'quiz', 'test'],
    run: () => void reviewCurrentNote(),
  },
  {
    id: 'study.review-all',
    title: 'Review All Flashcards',
    category: 'Study',
    icon: 'flashcard',
    description: 'Review every flashcard in the vault',
    keywords: ['revise', 'srs', 'study', 'deck'],
    global: true,
    run: () => void reviewWholeVault(),
  },
  {
    id: 'study.study-mode',
    title: 'Study Mode',
    category: 'Study',
    icon: 'book',
    description: 'Distraction-free study layout',
    keywords: ['focus', 'zen', 'distraction'],
    global: true,
    run: () => useStudy.getState().toggleStudyMode(),
  },
  {
    id: 'study.today',
    title: "Today's Date",
    category: 'Study',
    icon: 'calendar',
    description: "Insert today's date (YYYY-MM-DD)",
    keywords: ['date', 'now', 'day'],
    example: isoDate(),
    run: (ctx) => insertText(ctx.view, isoDate()),
  },
  {
    id: 'study.due',
    title: 'Due Date',
    category: 'Study',
    icon: 'reminder',
    description: 'Schedule a task on the calendar (📅 date)',
    keywords: ['deadline', 'schedule', 'calendar', 'task'],
    example: '- [ ] Task 📅 ' + isoDate(),
    run: snippet('- [ ] ${task} 📅 ' + isoDate()),
  },
  {
    id: 'study.practice',
    title: 'Practice Question',
    category: 'Study',
    icon: 'check',
    description: 'Question with hidden answer',
    keywords: ['exam', 'quiz'],
    run: snippet('**Q.** ${question}\n\n> [!toggle]- Answer\n> ${answer}'),
  },
  {
    id: 'study.exam-revision',
    title: 'Exam Revision',
    category: 'Study',
    icon: 'check',
    description: 'Revision checklist',
    keywords: ['exam', 'study'],
    run: snippet(
      '## ${Topic} — revision\n\n- [ ] Re-read notes\n- [ ] Summarise in my own words\n- [ ] Practice questions\n- [ ] Review weak points',
    ),
  },
  {
    id: 'study.formula-sheet',
    title: 'Formula Sheet',
    category: 'Study',
    icon: 'math',
    description: 'Key formulas table',
    keywords: ['cheat sheet'],
    run: snippet(
      '## Formula sheet\n\n| Formula | Meaning |\n| ------- | ------- |\n| $${formula}$ | ${meaning} |',
    ),
  },
  {
    id: 'study.worked-example',
    title: 'Worked Example',
    category: 'Study',
    icon: 'book',
    description: 'Step-by-step example',
    keywords: ['solution'],
    run: snippet(
      '> [!example] ${Problem}\n> **Step 1.** ${step}\n> **Step 2.** ${step}\n> **Answer:** ${answer}',
    ),
  },
  {
    id: 'study.definition',
    title: 'Definition',
    category: 'Study',
    icon: 'book',
    description: 'Definition block',
    keywords: ['term'],
    run: snippet('> [!definition] ${Term}\n> ${definition}'),
  },
  {
    id: 'study.key-concept',
    title: 'Key Concept',
    category: 'Study',
    icon: 'highlight',
    description: 'Highlighted key concept',
    keywords: ['important'],
    run: snippet('> [!important] Key concept\n> ${concept}'),
  },
  {
    id: 'study.summary',
    title: 'Summary',
    category: 'Study',
    icon: 'toc',
    description: 'Summary section',
    keywords: ['tldr', 'recap'],
    run: snippet('## Summary\n\n- ${point}'),
  },
  {
    id: 'study.important',
    title: 'Important Point',
    category: 'Study',
    icon: 'highlight',
    description: 'Highlighted important point',
    keywords: ['note'],
    run: snippet('==${important point}=='),
  },

  // ─────────────────────────── Media ───────────────────────────
  {
    id: 'media.image',
    title: 'Image',
    category: 'Media',
    icon: 'image',
    description: 'Insert an image from the vault (or add one)',
    keywords: ['picture', 'photo'],
    run: () => openAttachmentPicker(),
  },
  {
    id: 'media.pdf',
    title: 'PDF',
    category: 'Media',
    icon: 'file',
    description: 'Insert a PDF as a card that opens the viewer',
    keywords: ['document', 'lecture', 'link', 'card'],
    example: '[Lecture.pdf](Lecture.pdf)',
    run: () => openAttachmentPicker('link'),
  },
  {
    id: 'media.file',
    title: 'File',
    category: 'Media',
    icon: 'file',
    description: 'Attach any file from the vault (or add one)',
    keywords: ['attachment'],
    run: () => openAttachmentPicker(),
  },
  {
    id: 'media.attachment',
    title: 'Attachment',
    category: 'Media',
    icon: 'file',
    description: 'Choose a file from the vault or add a new one',
    keywords: ['upload', 'attach'],
    run: () => openAttachmentPicker(),
  },
  {
    id: 'media.video',
    title: 'Video',
    category: 'Media',
    icon: 'video',
    description: 'Embed a video file stored in the vault',
    keywords: ['mp4', 'movie'],
    example: '![[clip.mp4]]',
    run: snippet('![[${video.mp4}]]'),
  },
  {
    id: 'media.audio',
    title: 'Audio',
    category: 'Media',
    icon: 'audio',
    description: 'Embed an audio file stored in the vault',
    keywords: ['mp3', 'sound', 'recording'],
    example: '![[recording.mp3]]',
    run: snippet('![[${audio.mp3}]]'),
  },
  {
    id: 'media.code-snippet',
    title: 'Code Snippet',
    category: 'Media',
    icon: 'code',
    description: 'Fenced code snippet',
    keywords: ['code'],
    contexts: ['code'],
    run: snippet('```${language}\n${code}\n```'),
  },
  {
    id: 'media.mermaid',
    title: 'Mermaid Diagram',
    category: 'Media',
    icon: 'mermaid',
    description: 'Mermaid diagram code block',
    keywords: ['flowchart', 'graph', 'diagram'],
    example: '```mermaid\ngraph TD; A-->B;\n```',
    run: snippet('```mermaid\ngraph TD;\n  ${A} --> ${B};\n```'),
  },
  {
    id: 'media.table',
    title: 'Table',
    category: 'Media',
    icon: 'table',
    description: 'Markdown table',
    keywords: ['grid', 'rows'],
    contexts: ['table'],
    run: snippet(
      '| ${Column A} | ${Column B} |\n| ----------- | ----------- |\n| ${cell} | ${cell} |',
    ),
  },

  // ─────────────────────────── Embeds ───────────────────────────
  {
    id: 'embed.page',
    title: 'Embed Page',
    category: 'Embeds',
    icon: 'subpage',
    description: 'Embed another page (preview)',
    keywords: ['transclude'],
    example: '![[Page]]',
    run: (ctx) => insertText(ctx.view, '![[', 3),
  },
  {
    id: 'embed.heading',
    title: 'Embed Heading',
    category: 'Embeds',
    icon: 'subpage',
    description: 'Embed a section of a page',
    keywords: ['section'],
    example: '![[Page#Heading]]',
    run: snippet('![[${Page}#${Heading}]]'),
  },
  {
    id: 'embed.pdf',
    title: 'Embed PDF',
    category: 'Embeds',
    icon: 'file',
    description: 'Embed a scrollable PDF inline in the page',
    keywords: ['document', 'inline', 'scroll'],
    example: '![[Lecture.pdf]]',
    run: () => openAttachmentPicker('embed'),
  },
  {
    id: 'embed.mermaid',
    title: 'Embed Mermaid',
    category: 'Embeds',
    icon: 'mermaid',
    description: 'Mermaid diagram block',
    keywords: ['diagram'],
    run: snippet('```mermaid\n${flowchart LR; A-->B}\n```'),
  },
  {
    id: 'embed.youtube',
    title: 'Embed YouTube Link',
    category: 'Embeds',
    icon: 'video',
    description: 'Link to a YouTube video (offline-safe)',
    keywords: ['video', 'yt'],
    example: '[▶ Title](https://youtu.be/…)',
    run: snippet('[▶ ${Video title}](${https://youtu.be/...})'),
  },
  {
    id: 'embed.website',
    title: 'Embed Website',
    category: 'Embeds',
    icon: 'link',
    description: 'Link to a website (offline placeholder)',
    keywords: ['url', 'web'],
    example: '[Title](https://…)',
    run: snippet('[${Website title}](${https://...})'),
  },

  // ─────────────────────────── Organisation ───────────────────────────
  {
    id: 'org.new-page',
    title: 'New Page',
    category: 'Organisation',
    icon: 'page',
    description: 'Create a new top-level page',
    keywords: ['create'],
    run: () => runCommand('note.new'),
  },
  {
    id: 'org.new-subpage',
    title: 'New Subpage',
    category: 'Organisation',
    icon: 'subpage',
    description: 'Create a page inside this one',
    keywords: ['child'],
    run: () => runCommand('page.new-subpage'),
    disabledReason: getCommand('page.new-subpage') ? undefined : 'Open a page first',
  },
  {
    id: 'org.link-page',
    title: 'Link Existing Page',
    category: 'Organisation',
    icon: 'link',
    description: 'Wiki-link to another page',
    keywords: ['reference', 'connect'],
    example: '[[Page]]',
    run: (ctx) => insertText(ctx.view, '[[', 2),
  },
  {
    id: 'org.property',
    title: 'Page Property',
    category: 'Organisation',
    icon: 'properties',
    description: 'YAML frontmatter fields',
    keywords: ['frontmatter', 'metadata'],
    run: snippet('---\ntype: ${note}\ncourse: ${course}\ntags:\n  - ${tag}\n---\n${}'),
  },
  {
    id: 'org.tags',
    title: 'Tags',
    category: 'Organisation',
    icon: 'tag',
    description: 'Insert a #tag',
    keywords: ['label'],
    example: '#tag',
    run: (ctx) => insertText(ctx.view, '#'),
  },
  {
    id: 'org.breadcrumb',
    title: 'Breadcrumb',
    category: 'Organisation',
    icon: 'breadcrumb',
    description: 'Path to this page',
    keywords: ['path', 'location'],
    run: snippet('${Vault} / ${Section} / ${Page}'),
  },
  {
    id: 'org.toc',
    title: 'Table of Contents',
    category: 'Organisation',
    icon: 'toc',
    description: 'Outline placeholder',
    keywords: ['outline', 'contents'],
    run: snippet('## Contents\n\n- [[#${Heading}]]'),
  },
  {
    id: 'org.calendar',
    title: 'Calendar',
    category: 'Organisation',
    icon: 'calendar',
    description: "Open today's daily note",
    keywords: ['daily', 'date'],
    run: () => runCommand('daily.open-today'),
  },
  {
    id: 'org.reminder',
    title: 'Reminder',
    category: 'Organisation',
    icon: 'reminder',
    description: 'A reminder with a date',
    keywords: ['remind', 'alert'],
    run: snippet('- [ ] ⏰ ${reminder} (due ${' + isoDate() + '})'),
  },
  {
    id: 'org.task',
    title: 'Task',
    category: 'Organisation',
    icon: 'task',
    description: 'A to-do task',
    keywords: ['todo', 'checkbox'],
    contexts: ['list'],
    run: snippet('- [ ] ${task}'),
  },
  {
    id: 'org.due-date',
    title: 'Due Date',
    category: 'Organisation',
    icon: 'calendar',
    description: "Insert today's date",
    keywords: ['deadline', 'date'],
    run: (ctx) => insertText(ctx.view, isoDate()),
  },

  // ─────────────────────────── AI (optional, disabled until a plugin exists) ───────────────────────────
  {
    id: 'ai.rewrite',
    title: 'Rewrite',
    category: 'AI',
    icon: 'ai',
    description: 'Rewrite the selection',
    keywords: ['ai', 'paraphrase'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
  {
    id: 'ai.summarise',
    title: 'Summarise',
    category: 'AI',
    icon: 'ai',
    description: 'Summarise the selection',
    keywords: ['ai', 'tldr'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
  {
    id: 'ai.expand',
    title: 'Expand',
    category: 'AI',
    icon: 'ai',
    description: 'Expand the selection',
    keywords: ['ai', 'elaborate'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
  {
    id: 'ai.simplify',
    title: 'Simplify',
    category: 'AI',
    icon: 'ai',
    description: 'Simplify the selection',
    keywords: ['ai', 'plain'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
  {
    id: 'ai.generate-questions',
    title: 'Generate Questions',
    category: 'AI',
    icon: 'ai',
    description: 'Generate study questions',
    keywords: ['ai', 'quiz'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
  {
    id: 'ai.explain',
    title: 'Explain',
    category: 'AI',
    icon: 'ai',
    description: 'Explain the selection',
    keywords: ['ai', 'clarify'],
    run: () => {},
    disabledReason: 'Requires an AI plugin (none installed)',
  },
]

let registered = false

/**
 * Register every slash command into the slash registry AND the global command
 * palette (shared definitions). Idempotent.
 */
export function registerSlashCommands(): void {
  if (registered) return
  registered = true
  for (const command of SLASH_COMMANDS) {
    registerSlashCommand(command)
    // Mirror into the command palette so Ctrl/Cmd+K can run inserts too.
    registerCommand({
      id: `slash:${command.id}`,
      title: command.title,
      category: command.category,
      shortcut: command.shortcut,
      isAvailable: () => {
        if (command.disabledReason) return false
        if (command.global) return useVault.getState().status === 'ready'
        const tabs = useTabs.getState()
        const active = tabs.tabs.find((t) => t.id === tabs.activeId)
        return active?.type === 'note'
      },
      run: () => {
        const view = getActiveView()
        if (command.global) {
          command.run({ view: view as EditorView })
          return
        }
        if (view) command.run({ view })
      },
    })
  }
}
